DontShaveTheYak/cloud-radar

.github/workflows/release.yml

Fixed the step name when getting the tag output and configured publish to use test pypi.

Fix: Release workflow for TestPypi

---

README.md
mypy.ini
src/cloud_radar/cf/unit/_template.py
src/cloud_radar/cf/unit/functions.py
tests/test_cf/test_unit/test_functions.py
tests/test_cf/test_unit/test_template.py

Move Intrinsic functions to their own module and get most of [them](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) implemented.
Functions: 
1. [x] Fn::Base64
2. [x] Fn::Cidr
3. [x] Condition functions (This is like an entire new list) 🤔
4. [x] Fn::FindInMap
5. [x] Fn::GetAtt
6. [x] Fn::GetAZs
7. [x] Fn::ImportValue
8. [x] Fn::Join
9. [x] Fn::Select
10. [x] Fn::Split
11. [x] Fn::Sub
12. [x] Fn::Transform
13. [x] Ref

Refactor intrinsic functions

---

README.md
src/cloud_radar/cf/unit/_template.py
src/cloud_radar/cf/unit/functions.py
tests/test_cf/test_unit/test_functions.py
tests/test_cf/test_unit/test_template.py

Some functions restrict other functions from being nested inside of them. Before we didn't enforce those restrictions. This PR modifies the recursive resolve_values functions to use a passed-in dictionary to dispatch function calls. If a function is found but it not allowed then a Value error is thrown. 
In the future this should be refactored. it would be nice to know things like why is X not allowed. What is X nested in?

Enforce restrictions when using nested Intrinsic and Conditional functions.

---

.github/workflows/release.yml
.github/workflows/test.yml
noxfile.py
poetry.lock

According to https://github.com/python-poetry/poetry/issues/6300#issuecomment-1233211156 there were multiple bugs in our current version and a long list of versions broken by pypi. So we needed to upgrade anyways. Didnt see this issue when developing because we install the latest in the docker container. Maybe we shouldn't? Or maybe we should run the CICD in the docker container.

update poetry version

---

.scripts/bump.py

Poetry recently went from producing `tag-alpha` to `tag-a` which broke our ability to automatically tag and release versions.

Fix automated releases

---

src/cloud_radar/cf/unit/_template.py
src/cloud_radar/cf/unit/functions.py
tests/templates/log_bucket/log_bucket.yaml
tests/test_cf/test_examples/test_unit.py

This fixes a bug where `Conditions` in the template worked but not the `!Condition` intrinsic function. It also likely fixed a edge case where it was possible that instead of getting the result of the condition you would have gotten the unresolved value (an intrinsic function).
This was the result of several issues.
1. I didn't know about the `!Condition` intrinsic function because of the strange way it's documented on a seprate page away from both regular intrinsic functions and the other conditional intrinsic functions.
2. For whatever reason the full name for `!Condition` is NOT `Fn::Condition` like all the other conditional/intrinsic functions. Instead its full name is `Condition`. This means it was not caught by the existing logic that solves these functions by their full name.
It …

fix bug with nested conditions

---

src/cloud_radar/cf/unit/_template.py
src/cloud_radar/cf/unit/functions.py
tests/test_cf/test_unit/test_template.py

The PR fixes some undocumented behavior where you can call other nested functions (aka "supported functions") from inside a condition/intrinsic function that was not listed by the AWS docs.
1. Allow `Fn::Sub to be called from inside `Fn::Sub`. ([AWS Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html#w2ab1c31c28c64c13))
2. Allow `Fn::ImportValue` to be called from inside `Fn::If`. ([AWS Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#w2ab1c31c28c21c29))

Fix undocumented behavior in intrinsic functions

---

README.md
src/cloud_radar/cf/unit/_template.py
tests/test_cf/test_unit/test_template.py

See #220 for background. 
This is a draft & WIP. Just creating a PR just now to kind of show I've made a start on this (although it will be a few days till I get back to it). There are flake8 issues in this still. 
This currently works with the `PolicyName` example which includes a dynamic reference, and the case where the dynamic reference key contains a parameter which would be updated by an `Fn::Sub`. 
This is tackling it from the point of introducing a breaking change - once it _functionally_ works we can work out the best approach for breaking / non-breaking. It needs for tests for validation cases but I'll take a look at that in a few more days.

Add support for dynamic references

---

.github/workflows/release.yml

Recently pushes to test pypi started to fail because of some auth issue. It's probably a good idea to push to the real pypi anyway to make it easier for users to install the release candidates.

Push release candidates to the real PyPi

---

codecov.yml

We have lots of PRs that are failing because the codecov patch status check is too strict. This will allow PRs to pass even if the code coverage drops slightly.

add codecov config file

---

src/cloud_radar/cf/unit/_template.py
tests/test_cf/test_unit/test_template.py

I did not mean to refactor the entire function. I just didn't realize how many edge cases there were when handling dynamic references. I used chatGPT for the regex. It took many tries before it gave me a working one. When I asked it why it took so long for us to derive the correct answer, it replied with a very generic list of reasons of why it might have taken so long. The top of that list was miscommunication. I asked it if it thought we miscommunicated and surprisingly it was able to clearly articulate how we miscommunicated. I am both excited and afraid of what the next 10 years will bring.

allow ssm dynamic references to not include a version

---

src/cloud_radar/cf/unit/_template.py
tests/templates/log_bucket/log_bucket.yaml

Their Condition key was not being resolved correctly which caused the value for the entire resource to be set as the value from the condition. This caused the program to crash when trying to render the template. Thank to @dhutchison for both reporting the bug and coming up with this simple but elegant fix. See #246 for more details.

fix rendering of resources with a condition but not Properties

---

src/cloud_radar/cf/unit/_template.py
src/cloud_radar/cf/unit/functions.py
src/cloud_radar/cf/unit/test__template.py
tests/templates/test_maps.yml
tests/test_cf/test_examples/test_unit.py
tests/test_cf/test_unit/test_functions.py

This commit adds the groundwork for using Cloudformation hosted Transforms. The Transforms add or enhance the existing Cloudformation functionality.
The only Transform currently supported is the AWS::LanguageExtensions and it is only partially implemented. This commit only adds support for using a DefaultValue when using the !FindInMap function.
Releated to #271

Add the ability to use Cloudformation hosted Tranforms

---

examples/unit/parameters/ssm/SSM_Parameter_example.yaml
examples/unit/parameters/ssm/test_ssm_parameters.py
src/cloud_radar/cf/unit/_template.py

Fixes #316 . Updates regex used for validating SSM parameter keys to one that is based on AWS documentation.

Correct SSM parameter key regex

---

src/cloud_radar/cf/unit/functions.py
tests/test_cf/test_unit/test_functions.py

Implement caching for the `_fetch_region_data` function to reduce rate limiting issues encountered when fetching data from GitHub. This change optimizes data retrieval by storing results for subsequent requests.

Add caching to region data fetching

---

src/cloud_radar/cf/unit/_hooks.py
src/cloud_radar/cf/unit/functions.py
tests/test_cf/test_unit/test_functions.py

At work we were getting 403 denied on AWS, until I changed the user-agent.

change error handling when fetching regions from github and add user-agent

---

README.md
src/cloud_radar/cf/unit/functions.py
tests/templates/test_media_getatt.yaml
tests/test_cf/test_e2e/test_stack.py
tests/test_cf/test_unit/test_functions_get_att.py

Fixes #394 
I had started going down a bit of a rabbit hole of how hooks could be introduced so that attribute values could be more accurately generated, and that the library user could extend this instead of waiting on a library update to support new types. That seems quite complicated however for how infrequently I expect it to be required/used. The end of that approach was going to be that the hook updated the Metadata anyway (so calling GetAtt a second time for the same resource and attribute name would get a cached value so it was deterministic) - so if that idea comes back around, it will slot in to this fix. 
This change allows what `GetAtt` returns to be set by the resource Metadata in the template. When unit testing there are no real AWS resources created, and cloud-radar does …

Allow attribute values to come from resource metadata

---

README.md
src/cloud_radar/cf/unit/_template.py
tests/templates/test_stackid.yaml
tests/test_cf/test_unit/test_stack_stackid.py

Adds in a default value for the StackId property and a function to generate a StackId if it is not already set
Fixes #384

Add support for generating a StackId when rendering a template

---

src/cloud_radar/cf/unit/_template.py
src/cloud_radar/cf/unit/functions.py
src/cloud_radar/cf/unit/test__template.py
tests/test_cf/test_unit/test_template.py

This feature was based on the nested function limitations in the AWS CloudFormation documentation. However, in turns out that the AWS documentation is incorrect and nested functions are allowed in many places where the documentation says they are not. Since this feature was doing more harm than good, it has been removed.

remove check for nested intrinsic functions

---

src/cloud_radar/cf/unit/_template.py
tests/test_cf/test_unit/test_template.py

Fixes #171 
Improves error messages to include the names of the parameters which are incorrect.

fix(params): change error messages to include parameter names #171
